const $=id=>document.getElementById(id);
let mode='content', draft=null, workbookBytes=null, workbookName='', generation=0;
function status(message,kind='notice',target='status'){let e=$(target);e.className=kind;e.textContent=message}
function hideStatus(target='status'){$(target).className='hide'}
function switchMode(m){mode=m;generation++;draft=null;$('modeContent').classList.toggle('active',m==='content');$('modeTopics').classList.toggle('active',m==='topics');$('contentBrief').classList.toggle('hide',m!=='content');$('topicsBrief').classList.toggle('hide',m!=='topics');$('contentResult').classList.add('hide');$('topicsResult').classList.add('hide');$('draftBadge').classList.add('hide');$('empty').classList.remove('hide');$('generate').textContent=m==='topics'?'Prepare topics prompt':'Prepare content prompt';$('promptArea').classList.add('hide');$('pastedResult').value='';hideStatus();hideStatus('saveStatus')}
$('modeContent').onclick=()=>switchMode('content');$('modeTopics').onclick=()=>switchMode('topics');
$('trackerFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let b=new Uint8Array(await f.arrayBuffer());await inspectWorkbook(b);workbookBytes=b;workbookName=f.name;$('trackerStatus').textContent='Loaded '+f.name+' · ready for approval';$('download').classList.add('hide');hideStatus('saveStatus')}catch(err){workbookBytes=null;status('Could not read this tracker: '+err.message,'error','saveStatus')}};
function brief(){return{pillar:$('pillar').value,format:$('format').value,platform:$('platform').value,audience:$('audience').value,language:$('language').value,topic:$('topic').value.trim(),scope:$('scope').value,context:$('context').value.trim(),theme:$('theme').value.trim(),count:+$('count').value}}
const PAXU_RULES = `You are the PAXU® Content Writer. Write for the selected audience as a warm, direct, practical older sibling. Address one person as "bạn", not "các bạn". Use short natural lines, avoid fear or blame. PAXU® offers guidance and information; it is not a recruitment agency, housing provider, or bank. EMMAI® helps people compare options and choose safer steps; it does not promise outcomes. Captions may use icons at the start of lines, with #PAXU and relevant hashtags. Scripts, shot lists, voiceover and on-screen text must have no icons. Do not default to opening a Reels script with a question. Full Reels = script and caption, without a shot list or separate voiceover. Full AI Video/TVC = caption, shot list and voiceover, shots at most 10 seconds. Caption-only or script-only = only that requested component. For news, law, migration rules, wages, procedures, fees and other changing facts: verify current official sources where available, give direct source links in source_note, and avoid unsupported specifics. Topics-only means ideas without finished captions or scripts.`;
let pendingBrief=null,pendingMode=null;
function makePrompt(b,m){
  const common = PAXU_RULES + '\n\nSelected brief: ' + JSON.stringify(b);
  return m==='topics' ? common + `\n\nSuggest ${b.count} distinct topics only. Return exactly one JSON object: {"topics":[{"topic":"...","pillar":"...","format":"Graphic/Reels/AI Video/News Post","angle":"one concrete sentence","research_need":"what to verify, or none"}]}. No captions, scripts, hooks or voiceover. No markdown code fence.`
    : common + `\n\nCreate PAXU content. If the topic is blank, choose one concrete topic in the selected category. Return exactly one JSON object with these string keys: "topic", "pillar", "hook", "caption", "script", "shot_list", "voiceover", "on_screen_text", "visual_brief", "cta", "hashtags", "source_note". Use empty strings for unused fields. Respect the selected deliverable and format. No markdown code fence.`;
}
$('generate').onclick=()=>{
  let b=brief();if(mode==='content'&&!b.topic&&b.pillar==='Any')return status('Choose a category or enter a topic.','warn');
  pendingBrief=b;pendingMode=mode;draft=null;
  $('preparedPrompt').value=makePrompt(b,mode);$('pastedResult').value='';$('promptArea').classList.remove('hide');
  $('contentResult').classList.add('hide');$('topicsResult').classList.add('hide');$('empty').classList.remove('hide');$('draftBadge').classList.add('hide');
  status('Prompt ready. Copy it to ChatGPT, then paste the reply below.');
};
$('copyPrompt').onclick=async()=>{
  let prompt=$('preparedPrompt');
  try{await navigator.clipboard.writeText(prompt.value);status('Prompt copied. Open ChatGPT and paste it there.')}
  catch{prompt.focus();prompt.select();status('Prompt selected. Press Ctrl+C, then paste it into ChatGPT.','warn')}
};
function parseReply(text){
  let cleaned=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim();
  try{return JSON.parse(cleaned)}catch{throw Error('I could not read that reply. In ChatGPT, ask: "Return the same answer as valid JSON only, without a code fence." Then paste its complete reply.')}
}
$('showResult').onclick=()=>{
  if(!pendingBrief)return status('Prepare a prompt first.','warn');
  let raw=$('pastedResult').value.trim();if(!raw)return status('Paste ChatGPT’s reply first.','warn');
  try{let result=parseReply(raw);if(pendingMode==='topics')showTopics(result);else{if(typeof result.caption!=='string'||typeof result.script!=='string')throw Error('The reply is missing caption or script fields. Ask ChatGPT to return the requested JSON structure.');showContent(result,pendingBrief)}hideStatus()}
  catch(err){status(err.message,'error')}
};
function showTopics(r){if(!Array.isArray(r.topics))throw Error('Topics response could not be read. Try again.');$('empty').classList.add('hide');let box=$('topicsResult');box.replaceChildren();let h=document.createElement('h3');h.textContent=r.topics.length+' topic ideas';box.append(h);r.topics.forEach((t,i)=>{let d=document.createElement('div');d.className='topic';let strong=document.createElement('strong');strong.textContent=(i+1)+'. '+(t.topic||'Untitled');let meta=document.createElement('small');meta.textContent=[t.pillar,t.format].filter(Boolean).join(' · ');let p=document.createElement('p');p.textContent=t.angle||'';let n=document.createElement('small');n.textContent=t.research_need&&t.research_need!=='none'?'Research: '+t.research_need:'';let pick=document.createElement('button');pick.type='button';pick.className='action secondary';pick.textContent='Use this topic';pick.onclick=()=>{$('topic').value=t.topic||'';if(t.pillar&&[...$('pillar').options].some(o=>o.value===t.pillar))$('pillar').value=t.pillar;if(t.format&&[...$('format').options].some(o=>o.value===t.format))$('format').value=t.format;switchMode('content')};d.append(strong,meta,p,n,document.createElement('br'),pick);box.append(d)});box.classList.remove('hide')}
function showContent(r,b){draft={...r,topic:b.topic||String(r.topic||'').trim(),pillar:b.pillar==='Any'?(r.pillar||''):b.pillar,format:b.format,platform:b.platform,audience:b.audience,language:b.language,scope:b.scope};let box=$('outputFields');box.replaceChildren();let labels={caption:'Caption',script:'Script',shot_list:'Shot list',voiceover:'Voiceover',on_screen_text:'On-screen text',visual_brief:'Visual brief',cta:'CTA',hashtags:'Hashtags',source_note:'Research note'};let visible=b.scope==='caption'?['caption']:b.scope==='script'?['script']:b.format==='Reels'?['script','caption']:['caption','script','shot_list','voiceover','on_screen_text','visual_brief'];visible.push('cta','hashtags','source_note');for(let key of visible){if(!String(r[key]||'').trim()&&!['caption','script'].includes(key))continue;let wrap=document.createElement('div');wrap.className='field';let lab=document.createElement('label');lab.textContent=labels[key];lab.htmlFor='edit_'+key;let ta=document.createElement('textarea');ta.id='edit_'+key;ta.value=r[key]||'';ta.rows=key==='caption'||key==='script'?8:3;ta.oninput=()=>{draft[key]=ta.value;$('download').classList.add('hide');hideStatus('saveStatus')};wrap.append(lab,ta);box.append(wrap)}$('empty').classList.add('hide');$('contentResult').classList.remove('hide');$('draftBadge').classList.remove('hide');$('draftBadge').textContent='Draft · not saved';hideStatus('saveStatus')}
const NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main';function kids(node,local){return [...node.children].filter(e=>e.localName===local)}function cellValue(c,shared){if(!c)return'';if(c.getAttribute('t')==='inlineStr')return [...c.getElementsByTagNameNS(NS,'t')].map(n=>n.textContent).join('');let v=c.getElementsByTagNameNS(NS,'v')[0]?.textContent||'';return c.getAttribute('t')==='s'?shared[+v]||'':v}function colCell(row,col){return kids(row,'c').find(c=>c.getAttribute('r')===col+row.getAttribute('r'))}function getRows(sheet){let data=sheet.getElementsByTagNameNS(NS,'sheetData')[0];return{data,rows:kids(data,'row')}}function parseXML(str){let d=new DOMParser().parseFromString(str,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('Invalid workbook XML');return d}
async function inspectWorkbook(bytes){if(typeof JSZip==='undefined')throw Error('Excel component could not load');let zip=await JSZip.loadAsync(bytes);let path='xl/worksheets/sheet1.xml';if(!zip.file(path))throw Error('Content Tracker sheet was not found');let book=parseXML(await zip.file('xl/workbook.xml').async('string'));let names=[...book.getElementsByTagNameNS(NS,'sheet')].map(x=>x.getAttribute('name'));if(names[0]!=='Content Tracker')throw Error('Expected Content Tracker as first worksheet');let xml=parseXML(await zip.file(path).async('string')),shared=[];if(zip.file('xl/sharedStrings.xml')){let ss=parseXML(await zip.file('xl/sharedStrings.xml').async('string'));shared=[...ss.getElementsByTagNameNS(NS,'si')].map(si=>[...si.getElementsByTagNameNS(NS,'t')].map(t=>t.textContent).join(''))}let {rows}=getRows(xml),head=rows.find(r=>r.getAttribute('r')==='1');if(!head||cellValue(colCell(head,'G'),shared)!=='Topic'||cellValue(colCell(head,'K'),shared)!=='Caption')throw Error('This is not the expected PAXU tracker');return{zip,xml,rows,shared,path}}
function setCell(doc,row,col,value){let r=row.getAttribute('r'),c=colCell(row,col);if(!c){c=doc.createElementNS(NS,'c');c.setAttribute('r',col+r);let index=col.charCodeAt(0);let next=kids(row,'c').find(x=>x.getAttribute('r').charCodeAt(0)>index);row.insertBefore(c,next||null)}if(value==='')return;c.removeAttribute('t');while(c.firstChild)c.removeChild(c.firstChild);c.setAttribute('t','inlineStr');let is=doc.createElementNS(NS,'is'),t=doc.createElementNS(NS,'t');t.setAttribute('xml:space','preserve');t.textContent=String(value);is.append(t);c.append(is)}
function normalize(s){return String(s||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('vi')}
function buildId(rows,shared){let used=new Set(rows.map(r=>cellValue(colCell(r,'A'),shared)));let n=1,id;do{id='PAXU-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(n++).padStart(3,'0')}while(used.has(id));return id}
async function updateTracker(){let {zip,xml,rows,shared,path}=await inspectWorkbook(workbookBytes),match=rows.filter(r=>+r.getAttribute('r')>1&&normalize(cellValue(colCell(r,'G'),shared))===normalize(draft.topic));if(match.length>1)throw Error('Several tracker rows match this topic. Choose a more specific topic before saving.');let target=match[0];if(target&&cellValue(colCell(target,'K'),shared).trim())throw Error('This topic already has a caption in the tracker. Existing content has been protected.');if(target&&cellValue(colCell(target,'R'),shared).includes('Script:'))throw Error('This topic already has a script in the tracker. Existing content has been protected.');if(!target){target=rows.find(r=>+r.getAttribute('r')>1&&!['A','G','K','R'].some(c=>cellValue(colCell(r,c),shared).trim()));if(!target){let {data}=getRows(xml),max=Math.max(...rows.map(r=>+r.getAttribute('r')));target=xml.createElementNS(NS,'row');target.setAttribute('r',String(max+1));data.append(target)}setCell(xml,target,'A',buildId(rows,shared));setCell(xml,target,'G',draft.topic);setCell(xml,target,'C',draft.platform);setCell(xml,target,'D',draft.language);setCell(xml,target,'E',draft.pillar);setCell(xml,target,'H',draft.format);setCell(xml,target,'I',draft.audience);setCell(xml,target,'P','Draft')}
const guarded=(col,val)=>{if(val&&!cellValue(colCell(target,col),shared).trim())setCell(xml,target,col,val)};
guarded('J',draft.hook);guarded('K',draft.caption);guarded('L',draft.cta);guarded('M',draft.hashtags);guarded('N',draft.source_note);guarded('O',draft.shot_list||draft.visual_brief);let detail=[draft.script&&'Script:\n'+draft.script,draft.voiceover&&'Voiceover:\n'+draft.voiceover,draft.on_screen_text&&'On-screen text:\n'+draft.on_screen_text].filter(Boolean).join('\n\n');if(detail){let existingNotes=cellValue(colCell(target,'R'),shared).trim();if(existingNotes&&!existingNotes.includes('Script:')&&!existingNotes.includes('Voiceover:'))setCell(xml,target,'R',existingNotes+'\n\n'+detail);else guarded('R',detail)}if(['','Pending','Changes Requested'].includes(cellValue(colCell(target,'Q'),shared).trim()))setCell(xml,target,'Q','Approved');let orig=rows.filter(r=>cellValue(colCell(r,'A'),shared).trim()).map(r=>cellValue(colCell(r,'A'),shared));zip.file(path,new XMLSerializer().serializeToString(xml));let changed=new Uint8Array(await zip.generateAsync({type:'uint8array',compression:'DEFLATE'}));let verify=await inspectWorkbook(changed),ids=verify.rows.map(r=>cellValue(colCell(r,'A'),verify.shared));if(orig.some(x=>!ids.includes(x)))throw Error('Validation failed: an existing content ID is missing');let row=verify.rows.find(r=>r.getAttribute('r')===target.getAttribute('r'));if(draft.caption&&cellValue(colCell(row,'K'),verify.shared)!==draft.caption)throw Error('Validation failed: caption did not save');return{changed,row:+target.getAttribute('r')}}

function setExcelChoice(){let enabled=$('addToExcel').checked;$('excelOptions').classList.toggle('hide',!enabled);$('approve').textContent=enabled?'Approve & update Excel':'Approve content';$('download').classList.add('hide');hideStatus('saveStatus')}
$('addToExcel').onchange=setExcelChoice;
$('approve').onclick=async()=>{
  if(!draft)return;
  if(!draft.topic)return status('Choose a topic before approval.','warn','saveStatus');
  if(!(draft.caption||draft.script||'').trim())return status('Add a caption or script before approval.','warn','saveStatus');
  if(!$('addToExcel').checked){$('draftBadge').textContent='Approved · not added to Excel';status('Content approved. No workbook was changed.','notice','saveStatus');return}
  if(!workbookBytes)return status('Choose your current .xlsx tracker first.','warn','saveStatus');
  $('approve').disabled=true;
  try{
    let result=await updateTracker();workbookBytes=result.changed;
    workbookName=workbookName.replace(/_Approved_\d{4}-\d{2}-\d{2}/,'').replace(/\.xlsx$/i,'')+'_Approved_'+new Date().toISOString().slice(0,10)+'.xlsx';
    $('trackerStatus').textContent='Updated in this page: '+workbookName;
    $('download').classList.remove('hide');$('draftBadge').textContent='Approved · Excel ready';
    status('Added to row '+result.row+'. Download the updated workbook to keep it.','notice','saveStatus');
    $('download').click();
  }catch(err){status(err.message,'error','saveStatus')}
  finally{$('approve').disabled=false}
};
$('download').onclick=()=>{let url=URL.createObjectURL(new Blob([workbookBytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));let a=document.createElement('a');a.href=url;a.download=workbookName;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
